services:
  jupyter:
      image: edu-docker-env:latest
      ports:
          - 8888:8888
      volumes:
          - type: bind
            source: ${HOME}/docker
            target: /home/jovyan
      environment:
          JUPYTER_ENABLE_LAB: "yes"
          JUPYTER_TOKEN: "go" # effectively disable authentication by setting to an easy password 0000
